---
- name: Elasticsearch with custom configuration
  hosts: elastic01
  become: yes
  become_user: root
  roles:
    - { role: ansible-elasticsearch, 
        es_instance_name: inventory_hostname,
        es_enable_xpack: false,
        es_config: {
          network.host: "{{hostvars[inventory_hostname].ansible_default_ipv4.address}}"
        }
      }
    - role: kibana
  vars:
    es_scripts: false
